/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

    public static void main(String[] args) {

        Contador contador = new Contador();

        contador.setContador(14);
        contador.incrementaContador();
        contador.getContador();

    }
}
