/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import edu.princeton.cs.algs4.Draw;
import edu.princeton.cs.algs4.DrawListener;

import javax.swing.*;
import java.util.ArrayDeque;

public class App implements DrawListener {

    private Draw draw;

    public App(){
        this.draw = new Draw();
        this.draw.setCanvasSize(1200, 600);
        this.draw.setXscale(0, 1200);
        this.draw.setYscale(0, 600);
        this.draw.enableDoubleBuffering();
        this.draw.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.draw.setTitle("jogo de cartas");
        this.draw.addListener(this);
        this.draw.clear(Draw.GREEN);
        this.draw.show();

        this.baralho = new ArrayDeque<>();


        CartaGrafica cg = new CartaGrafica(Naipe.COPAS,Valores.AS, 53, 45, true);

        for (Naipe naipe : Naipe.values()){
            for (Valores valor : Valores.values()){
                Carta c = new Carta(naipe, valor );
                baralho.add(carta);
            }
        }

        for (Carta c : baralho){
            c.desenharCarta(this.draw);
        }
    }



    @Override
    public void mouseClicked(double x, double y) {
        this.draw.picture(x, y, "cartas/1p.png");
        this.draw.show();

    }

    public static void main(String[] args) {
        App app = new App();



    }
}
