/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

import java.util.Random;

public class App {

    public static void main(String[] args) {


        System.out.println(args[0]);
        System.out.println(args[1]);





//        for (int i = 0; i < 4; i++) {
//            System.out.println("java");
//        }


//        String a = "POO";
//        String b = "ifsc";
//        int i = 10;
//        char c = a.charAt(0);
//        String d = "Eng" + "enharia " + b + " " + a + " " + i + " " + c;
//        System.out.println(d);

//
//        if (a.equalsIgnoreCase("poo")) {
//            System.out.println("iguais");
//        }
//        else {
//            System.out.println("diferentes");
//        }




//        Random r = new Random();
//        int numero = 0;
//        for (int i = 0; i < 5; i++) {
//            numero = r.nextInt(10);
//            System.out.println(numero);
//        }


//        System.out.println("Olá mundo!");
//        int ano = 2025;
//        for (int i = 0; i < 5; i++) {
//            System.out.println(i);
//        }
//        ano++;
//        System.out.println("fim do programa! " + ano);



//        int ano = 2025;
//        System.out.println(ano++);
//        System.out.println(++ano);




    }
}
