/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;

public class App {

    private HashMap<String, Livro> acervo = new HashMap<>();

    public static void main(String[] args) {

        App app = new App();

        HashMap<String, Livro> acervo = new HashMap<>();

        Livro a = new Livro("948", "Java", "Deitel", 2001);
        Livro b = new Livro("678", "C++", "Deitel", 2002);
        Livro c = new Livro("345", "Cálculo", "Maria", 1990);

        acervo.put(a.getiSBN(), a);
        acervo.put(b.getiSBN(), b);
        acervo.put(c.getiSBN(), c);

        acervo.forEach((k, v) -> {

            IO.println(String.format("Chave: %s\nValor: %s\n", k, v));

        });

        for (Livro livro : acervo.values()) {
            IO.println(livro);
        }

        List<String> lista = Arrays.asList("Java", "Stream", "API", "Collections");

        for (String lista2 : lista){

            int maior;

        }


        /*
        1 - Cadastrar Livro, sem iSBM duplicado
        2 - Listar iSBN de todos os livros
        3 - Consultar livro por iSBN e imprimir todos os dados do livro
        4 - Consultar livro por autor e imprimir todos os dados do(s) livros
        5 - Atualizar dados de um livro
        6 - Remover um livro pelo iSBN
        7 - Sair
         */

        boolean executando = true;

        while (executando) {
            IO.println("""
                    
                    Menu de Gerenciamento da Livraria
                                        
                    1 - Cadastrar Livro, sem iSBM duplicado
                    2 - Listar iSBN de todos os livros
                    3 - Consultar livro por iSBN e imprimir todos os dados do livro
                    4 - Consultar livro por autor e imprimir todos os dados do(s) livros
                    5 - Atualizar dados de um livro
                    6 - Remover um livro pelo iSBN
                    7 - Sair
                    
                    """);
            String opcao = IO.readln("Selecione a opção desejada: ");

            switch (opcao) {

                case "1" -> app.cadastrarLivro();

                case "2" -> app.listar();

                case "3" -> app.consultarISBN();

                case "4" -> app.consultarAutor();

                case "5" -> app.atualizarDados();

                case "6" -> app.removerLivro();

                case "7" -> {
                    IO.println("Saindo do menu...");
                    executando = false;
                }
            }


        }
    }


    public void cadastrarLivro(){
        String iSBN = IO.readln("Entre com o iSBN: ");
        String titulo = IO.readln("Entre com o título: ");
        String autor = IO.readln("Entre com o autor: ");
        int ano = Integer.parseInt(IO.readln("Entre com o ano de publicação: "));

        if (!acervo.containsKey(iSBN)){
            acervo.put(iSBN, new Livro(iSBN, titulo, autor, ano));
        }
        else{
            IO.println("iSBN " + iSBN + " já existente");
        }
    }

    public void listar(){
//        acervo.forEach((k, v) ->
//                IO.println(String.format("Chave: %s\n", k)));

        // ou

        for(String isbn : acervo.keySet()){
            IO.println("Chave: " + isbn);
        }
    }

    public void consultarISBN (){
        String iSBN = IO.readln("Entre com o iSBN: ");

        if (acervo.containsKey(iSBN)){
            Livro l = acervo.get(iSBN);
            IO.println("Nome do livro: " + l.getTitulo());
            IO.println("Nome do autor: " + l.getAutor());
            IO.println("Ano de publicação: " + l.getAno());
        }
        else {
            IO.println("Livro não encontrado");
        }
    }

    public void consultarAutor(){
        String autor = IO.readln("Entre com o nome do autor: ");

        for (Livro livro : acervo.values()) {
            if (livro.getAutor().equals(autor)){
                IO.println("iSBN: " + livro.getiSBN() + " / Nome do livro: " + livro.getTitulo() + " / Ano de lançamento: " + livro.getAno());
            }
            else{
                IO.println("Autor não encontrado");
            }
        }
    }

    public void atualizarDados() {
        String iSBN = IO.readln("Para atualizar os dados, primeiro entre com o iSBN do livro escolhido: ");

        Livro j = acervo.get(iSBN);
        if (!acervo.containsKey(iSBN)) {
            IO.println("Livro não encontrado");
        }
        else {
            String opcao = IO.readln("""
                    1 - Alterar titulo
                    2 - Alterar autor
                    3 - Alterar ano de lançamento
                    Selecione a opção: 
                    """);
            switch (opcao){
                case "1" -> j.setTitulo(IO.readln("Insira o novo título: "));

                case "2" -> j.setAutor(IO.readln("Insira o novo autor: "));

                case "3" -> j.setAno(Integer.parseInt(IO.readln("Insira o novo ano: ")));

            }
        }
    }

    public void removerLivro(){
        String iSBN = IO.readln("Entre com o iSBN para remover: ");
        if (acervo.containsKey(iSBN)) {
            acervo.remove(iSBN);
            IO.println("Livro " + iSBN + " removido da livraria");
        }
        else{
            IO.println("Livro não encontrado");

        }
    }
}