/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.HashMap;

public class App {

    private HashMap<String, Livro> acervo = new HashMap<>();

    public static void main(String[] args) {

        App app = new App();

        HashMap<String, Livro> acervo = new HashMap<>();

        Livro a = new Livro("948", "Java", "Deitel", 2001);
        Livro b = new Livro("678", "C++", "Deitel", 2002);
        Livro c = new Livro("345", "Cálculo", "Maria", 1990);

        acervo.put(a.getiSBN(), a);
        acervo.put(b.getiSBN(), b);
        acervo.put(c.getiSBN(), c);

        acervo.forEach((k, v) -> {

            IO.println(String.format("Chave: %s\nValor: %s\n", k, v));

        });

        for (Livro livro : acervo.values()) {
            IO.println(livro);
        }


        /*
        1 - Cadastrar Livro, sem iSBM duplicado
        2 - Listar iSBN de todos os livros
        3 - Consultar livro por iSBN e imprimir todos os dados do livro
        4 - Consultar livro por autor e imprimir todos os dados do(s) livros
        5 - Atualizar dados de um livro
        6 - Remover um livro pelo iSBN
        7 - Sair
         */

        boolean executando;

        while (executando = true) {
            IO.println("""
                    Menu de Gerenciamento da Livraria
                    
                    Selecione uma das opções abaixo:
                    
                    1 - Cadastrar Livro, sem iSBM duplicado
                    2 - Listar iSBN de todos os livros
                    3 - Consultar livro por iSBN e imprimir todos os dados do livro
                    4 - Consultar livro por autor e imprimir todos os dados do(s) livros
                    5 - Atualizar dados de um livro
                    6 - Remover um livro pelo iSBN
                    7 - Sair
                    
                    """);
            String opcao = IO.readln();

            switch (opcao) {

                case "1":
            }


        }
    }


    public void cadastrarLivro(){
        String iSBN = IO.readln("Entre com o iSBN: ");
        String titulo = IO.readln("Entre com o título: ");
        String autor = IO.readln("Entre com o autor: ");
        int ano = Integer.parseInt(IO.readln("Entre com o ano de publicação: "));

        if (!acervo.containsKey(iSBN)){
            acervo.put(iSBN, new Livro(iSBN, titulo, autor, ano));
        }
    }

    public void listar(){
        acervo.forEach((k, v) ->
                IO.println(String.format("Chave: %s\n", k)));

        // ou

        for(String isbn : acervo.keySet()){
            IO.println(isbn);
        }
    }

    public void consultarISBN (){
        String iSBN = IO.readln("Entre com o iSBN: ");

        if (acervo.containsKey(iSBN)){
            Livro l = acervo.get(iSBN);
            IO.println(l);
        }
    }

    public void consultarAutor(){
        String autor = IO.readln("Entre com o o nome do autor: ");

        if (acervo.containsKey(autor)){
            IO.println(acervo.get(autor));
        }
    }

    public void atualizarDados() {
        String iSBN = IO.readln("Para atualizar os dados, primeiro entre com o iSBN do livro escolhido: ");

        Livro j = acervo.get(iSBN);
        if (!acervo.containsKey(iSBN)) {
            IO.println("Livro não encontrado");
        }
        else {
            int opcao = 0;
            switch (opcao){
                case 1 -> j.setTitulo(IO.readln("Insira o novo título: "));

                case 2 -> j.setAutor(IO.readln("Insira o novo autor: "));

                case 3 -> j.setAno(Integer.parseInt(IO.readln("Insira o novo ano: ")));

            }
        }
    }

    public void removerLivro(){
        String iSBN = IO.readln("Entre com o iSBN: ");
        Livro p = acervo.get(iSBN);
        acervo.remove(p);
    }
}