/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

    public static void main(String[] args) {

        Horario h = new Horario(23,0,80);

        IO.println(h);



    }
}
