/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

    public static void main(String[] args) {

        Horario h = new Horario(21,19,18);

        IO.println(h);

        IO.println(h.paraExtenso());




    }
}
