/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

import java.time.LocalDate;

public class App {

    public static void main(String[] args) {

        int dia = Integer.parseInt(IO.readln("Entre com o dia: "));
        String mes = IO.readln("Entre com o mẽs: ");

        LocalDate data = LocalDate.parse(mes);



    }

}
