/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.lang.classfile.instruction.SwitchCase;
import java.util.ArrayList;

public class App {

    private ArrayList<Conta> contas;

    public App() {
        this.contas = new ArrayList<>();
    }

    public void menu(int opcao){

        int op;
        do{
            op = Integer.parseInt(IO.readln("Entre com a opção: "));
        }
        while (op!=5);

        // TODO implementar switch case

        String nome = IO.readln("Entre com o nome do titular: ");
        String numero = IO.readln("Entre com o numero da conta: ");
        double saldo = Double.parseDouble(IO.readln("Entre com o saldo: "));

       switch (op) {
           case 1 -> {
               Conta c = new Conta(nome, numero, 0);
               contas.add(c);
           }
           case 2 -> {
               IO.println(contas);
           }
           case 3 -> {
               contas.forEach(elemento ->{
                    for (Conta c : this.contas) {
                        if (elemento.getNumero().equals(numero)) {
                            elemento.depositar(saldo);
                            break;
                        }
                    }});
           }
           case 4 -> {
               contas.forEach(elemento ->{
                   for (Conta c : this.contas) {
                       if (elemento.getNumero().equals(numero)){
                       elemento.sacar(saldo);
                   }
               }});
           }
           case 5 -> {
                
           }
       }

    }

    public static void main(String[] args) {

        //ArrayList<String> lista = new ArrayList<>();
        var lista = new ArrayList<String>();

//        var s = "Juca"; // var -> inferencia de tipos: já sabe que é string
//        var i = 10; // var -> inferencia de tipos: já sabe que é inteiro

//        lista.add("Juca");
//        lista.add("Maria");
//        lista.add("Pedro");
//
//        String nome = lista.get(1);
//        IO.println(nome);
//
//        lista.add(1, "João");
//
//        nome = lista.get(1);
//        IO.println(nome);
//
//        IO.println(lista.size());
//
//
//        //imprimir todos da coleção
//        IO.println(lista);
//
//        //percorrer todos os elementos da coleção e imprimir somente Maria
//        //for each
//        for (String elemento: lista) {
//            if (elemento.equals("Maria")){
//                IO.println(elemento);
//            }
//        }
//
//        //com expressões lambda
//        lista.forEach(elemento -> {
//            IO.println(elemento);
//        });
//
//        lista.forEach(elemento -> {
//            if (elemento.equals("Maria")){
//            IO.println(elemento);
//        }});
//
//        //method reference
//        lista.forEach(IO::println);
//
//        //remover Maria
//        lista.removeIf(elemento -> elemento.equals("Maria"));
//        IO.println(lista);

        //Menu com 5 opcoes
        // 1 - Criar conta
        // 2 - listar todas contas
        // 3 - Depositar
        // 4 - Sacar
        // 5 - sair

        App app = new App();

        app.menu(1);

    }

    public void criarConta(){
        String nome = IO.readln("Entre com o nome do titular: ");
        String numero = IO.readln("Entre com o numero da conta: ");
        double saldo = 0;

        if(!contas.contains(numero)) {
            Conta conta = new Conta(nome, numero, 0);
            contas.add(conta);
            IO.println("Conta criada. Saldo = R$0,00 ");
        }
        else {
            IO.println("Conta já existente. Escolha outro número");
        }
    }

    public void listarContas(){
        for (Conta lista : contas){
            IO.println(lista.toString());
        }
    }

    public void depositar(){
        String numero = IO.readln("Entre com o numero da conta: ");

            for (Conta t : contas){
                if (t.getNumero().equals(numero)){
                t.depositar(Double.parseDouble(IO.readln("Valor para depositar: ")));
                }
            }
        }


    }
}







