/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.lang.classfile.instruction.SwitchCase;
import java.util.ArrayList;

public class App {

    private ArrayList<Conta> contas;

    public App() {
        this.contas = new ArrayList<>();
    }

    public void menu(int opcao){

        // TODO implementar switch case

        String n = IO.readln("Entre com o nome do titular: ");
        String num = IO.readln("Entre com o numero da conta: ");
        double s = Double.parseDouble(IO.readln("Entre com o saldo: "));

       switch (opcao) {
           case 1 -> {
               Conta c = new Conta(n, num, s);
               contas.add(c);
           }
           case 2 -> {
               IO.println(contas);
           }
           case 3 -> {
               contas.forEach(elemento ->{
                   if (elemento.getNumero().equals(num)){
                       elemento.depositar(s);
                   }
               });
           }
           case 4 -> {
               contas.forEach(elemento ->{
                   if (elemento.getNumero().equals(num)){
                       elemento.sacar(s);
                   }
               });
           }
           case 5 -> {
                
           }
       }

    }

    public static void main(String[] args) {

        //ArrayList<String> lista = new ArrayList<>();
        var lista = new ArrayList<String>();

//        var s = "Juca"; // var -> inferencia de tipos: já sabe que é string
//        var i = 10; // var -> inferencia de tipos: já sabe que é inteiro

//        lista.add("Juca");
//        lista.add("Maria");
//        lista.add("Pedro");
//
//        String nome = lista.get(1);
//        IO.println(nome);
//
//        lista.add(1, "João");
//
//        nome = lista.get(1);
//        IO.println(nome);
//
//        IO.println(lista.size());
//
//
//        //imprimir todos da coleção
//        IO.println(lista);
//
//        //percorrer todos os elementos da coleção e imprimir somente Maria
//        //for each
//        for (String elemento: lista) {
//            if (elemento.equals("Maria")){
//                IO.println(elemento);
//            }
//        }
//
//        //com expressões lambda
//        lista.forEach(elemento -> {
//            IO.println(elemento);
//        });
//
//        lista.forEach(elemento -> {
//            if (elemento.equals("Maria")){
//            IO.println(elemento);
//        }});
//
//        //method reference
//        lista.forEach(IO::println);
//
//        //remover Maria
//        lista.removeIf(elemento -> elemento.equals("Maria"));
//        IO.println(lista);

        //Menu com 3 opcoes
        // 1 - Criar conta
        // 2 - listar todas contas
        // 3 - Depositar
        // 4 - Sacar
        // 5 - sair

        App app = new App();

        app.menu(1);

    }
}
