/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

    public static void main(String[] args) {

        Aldeao aldeao = new Aldeao();
        IO.println(aldeao.atacar());
        IO.println(aldeao.mover());

        Arqueiro arqueiro = new Arqueiro();
        IO.println(arqueiro.atacar());
        IO.println(arqueiro.mover());

        Cavaleiro cavaleiro = new Cavaleiro();
        IO.println(cavaleiro.atacar());
        IO.println(cavaleiro.mover());
    }
}
