/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

    public static void main(String[] args) {

        Personagem[] personagens = new Personagem[3];
        personagens[0] = new Aldeao();
        personagens[1] = new Arqueiro();
        personagens[2] = new Cavaleiro();

        for (Personagem p : personagens){
            IO.println(p.mover());
            IO.println(p.atacar());

        }
    }
}
