/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {


    public static void main(String[] args) {

        Retangulo r = new Retangulo();

        System.out.println(r.calcularArea(3, 4));


    }
}
