/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

    public static void main(String[] args) {


        Horario h = new Horario();

        h.setHorario(23,40,40);











//        Carro fusca = new Carro("Fusca", 80);
//        Carro fusca2 = new Carro("Fusca");
//
//        Carro lambo = new Carro("Lambo", 400);
//
//
//        IO.println(fusca);






//        Pessoa p = new Pessoa("Gustavo", "1234567890", "gugugoedert@gmail.com");
//
//        IO.println(p);



    }
}
