/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

    public static void main(String[] args) {


//        Horario h = new Horario();
//
//        h.setHorario(13,40,40);
//        IO.println(h);
//
//        h.setHorario(3,2);
//        IO.println(h);
//
//        h.setHorario(3,2);
//        IO.println(h);
//
//        h.setHorario(3, 5);
//        IO.println(h);











        Carro fusca = new Carro("Fusca", 80);
//        Carro fusca2 = new Carro("Fusca");

        Carro lamborghini = new Carro("Lambo", 400);


        IO.println(lamborghini.modelo + " " + lamborghini.acelerar(200));






//        Pessoa p = new Pessoa("Gustavo", "1234567890", "gugugoedert@gmail.com");
//
//        IO.println(p);



    }
}
