/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import javax.swing.text.MaskFormatter;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.InputMismatchException;
import java.util.Scanner;

public class App {

    static String formatar (String mascara, String valor) throws ParseException {

//        MaskFormatter maskFormatter = null;
//        maskFormatter = new MaskFormatter(mascara);



        return "fim";
    }


    public static void main(String[] args) {

        String s = null;
        try {
            s = formatar("(##)", "48");
        } catch (ParseException e) {
            throw new RuntimeException(e);
        }
        IO.println(s);

//        Caixa<String> c = new Caixa<>("Olá mundo");
//        Caixa<Pessoa> d = new Caixa<>(new Pessoa("João"));
//        String s = c.getConteudo();
//        Pessoa errado = d.getConteudo();
//        ArrayList<String> a;
//        HashMap<String, String> b;


//        Scanner ler = new Scanner(System.in);
//        int a, b;
//
//        try{
//            System.out.println("Entre com numero");
//            a = ler.nextInt();
//            System.out.println("entre com numero");
//            b = ler.nextInt();
//
//            int res = a / b;
//
//            System.out.println(a + " dividido por " + b + " = " + res);
//        }catch (InputMismatchException e){
//            System.err.println("Só é permitido numeros inteiros");
//            ler.nextLine();
//        }
//
//        catch (ArithmeticException w){
//            System.err.println("Não divida por 0");
//            ler.nextLine();
//        }
//
//        catch (Exception z){
//            System.err.println("Comportamento inesperado");
//            ler.nextLine();
//        }
//
//        System.out.println("Fim do programa");





    }
}
