/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

public class App {

    public static void main(String[] args) {

        Lampada a = new Lampada();
        Lampada b = new Lampada();


        System.out.println(a.isLigada());;
        a.ligaDesliga();
        System.out.println(a.isLigada());
        System.out.println(b.isLigada());


    }
}
