/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;


import java.util.Random;

public class App {

    public static void main(String[] args) {

        Random r = new Random();
        int numeroSorteado = r.nextInt(100) + 1;

        int userPick = Integer.parseInt(IO.readln("Acerte o número!: "));

        int contadorTentativas = 1;

        while (numeroSorteado != userPick) {

            if (numeroSorteado < userPick) {
                contadorTentativas++;
                userPick = Integer.parseInt(IO.readln("O número é MENOR. Tente novamente: "));
            }

            if (numeroSorteado > userPick) {
                contadorTentativas++;
                userPick = Integer.parseInt(IO.readln("O número é MAIOR. Tente novamente: "));
            }

        }

        IO.println("Parabéns, você acertou! Total de tentativas:  " + contadorTentativas);
    }
}