/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;


import java.util.Random;

public class App {

    public static void main(String[] args) {

        Random r = new Random();
        int sorteado = r.nextInt(100);

        int userPick = Integer.parseInt(IO.readln("Acerte o número!: "));

        int contadorTentativas = 0;

        while (sorteado != userPick){
            IO.println("Você errou, tente novamente.");
            return;
        }

//        if (sorteado == userPick) {
//            IO.println("Parabéns, você acertou!: " + sorteado);
        }
    }
